# Generated by Django 4.2.16 on 2024-10-10 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('database_uri', models.CharField(default='', max_length=255)),
            ],
            options={
                'db_table': 'organizations',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OrgTables',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('table_name', models.CharField(max_length=100)),
                ('table_schema', models.TextField()),
                ('column_descriptions', models.JSONField()),
                ('column_types', models.JSONField()),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='effbi_api.organization')),
            ],
            options={
                'db_table': 'organization_tables',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='effbi_api.organization')),
            ],
            options={
                'db_table': 'users',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserAccessPermissions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('permission', models.CharField(choices=[('Admin', 'Admin'), ('View', 'View')], max_length=100)),
                ('table_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='effbi_api.orgtables')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='effbi_api.user')),
            ],
            options={
                'db_table': 'user_access_permissions',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dash_id', models.IntegerField(default=0)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('sql_query', models.TextField(blank=True, null=True)),
                ('tile_props', models.JSONField(blank=True, default=dict, null=True)),
                ('component', models.CharField(default='', max_length=100)),
                ('organization', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='effbi_api.organization')),
            ],
            options={
                'db_table': 'tiles',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('dash_id', models.IntegerField(editable=False, unique=True)),
                ('created_by', models.CharField(default='', max_length=100)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='effbi_api.organization')),
                ('tiles', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='effbi_api.tile')),
            ],
            options={
                'db_table': 'dashboards',
                'managed': True,
            },
        ),
    ]
