# Generated by Django 4.2.16 on 2024-10-13 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('effbi_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='orgtables',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
