# Generated by Django 4.2.16 on 2024-10-14 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('effbi_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='dash_id',
            field=models.IntegerField(editable=False),
        ),
    ]
