# Generated by Django 4.2.16 on 2024-10-13 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('effbi_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='database_uri',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        # migrations.AlterField(
        #     model_name='orgtables',
        #     name='id',
        #     field=models.AutoField(primary_key=True, serialize=False),
        # ),
    ]
