# Generated by Django 4.2.16 on 2024-10-08 04:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('effbi_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='database_uri',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=100, primary_key=True, serialize=False),
        ),
    ]
