# Generated by Django 4.2.16 on 2024-10-14 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('effbi_api', '0002_alter_organization_database_uri_alter_orgtables_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgtables',
            name='table_description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='dash_id',
            field=models.IntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='orgtables',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
