# Generated by Django 4.2.16 on 2024-10-19 03:40

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('effbi_api', '0002_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='super_user',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None),
        ),
    ]
