# Generated by Django 4.2.16 on 2024-10-08 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('effbi_api', '0002_alter_organization_database_uri'),
        ('effbi_api', '0002_change_user_id_to_char'),
    ]

    operations = [
    ]
