# Generated by Django 4.2.16 on 2024-10-17 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('effbi_api', '0003_orgtables_table_description_alter_dashboard_dash_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgtables',
            name='id',
            field=models.AutoField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
