# Generated by Django 4.2.16 on 2024-10-20 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('effbi_api', '0003_organization_super_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccesspermissions',
            old_name='table_id',
            new_name='table',
        ),
        migrations.RenameField(
            model_name='useraccesspermissions',
            old_name='user_id',
            new_name='user',
        ),
    ]
