# Generated by Django 4.2.16 on 2024-10-08 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('effbi_api', '0004_remove_user_created_at_remove_user_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='updated_at',
        ),
        migrations.CreateModel(
            name='UserAccessPermissions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('permission', models.CharField(choices=[('Admin', 'Admin'), ('View', 'View')], max_length=100)),
                ('table_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='effbi_api.orgtables')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='effbi_api.user')),
            ],
            options={
                'db_table': 'user_access_permissions',
                'managed': True,
            },
        ),
    ]
