# Generated by Django 4.2.16 on 2024-10-22 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('effbi_api', '0004_rename_table_id_useraccesspermissions_table_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccesspermissions',
            old_name='table',
            new_name='table_id',
        ),
        migrations.RenameField(
            model_name='useraccesspermissions',
            old_name='user',
            new_name='user_id',
        ),
    ]
