# Generated by Django 4.2.16 on 2024-10-08 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('effbi_api', '0004_remove_user_created_at_remove_user_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='updated_at',
        ),
    ]
