# Generated by Django 4.2.16 on 2024-10-09 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('effbi_api', '0006_dashboard_tile_dashboard_tiles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dashboard',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='dashboard',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='effbi_api.user'),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='dash_id',
            field=models.CharField(default=models.F('id'), max_length=100),
        ),
        migrations.AddField(
            model_name='tile',
            name='tile_props',
            field=models.JSONField(default=dict),
        ),
    ]
