# Generated by Django 4.2.16 on 2024-10-09 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('effbi_api', '0007_rename_name_dashboard_title_dashboard_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='created_by',
            field=models.CharField(default='', max_length=100),
        ),
    ]
