# Generated by Django 4.2.16 on 2024-10-09 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('effbi_api', '0008_alter_dashboard_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='tile',
            name='dash_id',
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='dash_id',
            field=models.IntegerField(editable=False, unique=True),
        ),
    ]
