# Generated by Django 4.2.16 on 2024-10-09 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('effbi_api', '0009_tile_dash_id_alter_dashboard_dash_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tile',
            old_name='name',
            new_name='title',
        ),
    ]
