# Generated by Django 4.2.16 on 2024-10-09 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('effbi_api', '0010_rename_name_tile_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tile',
            name='dashboard_id',
        ),
        migrations.AlterField(
            model_name='tile',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='tile',
            name='sql_query',
            field=models.TextField(null=True),
        ),
    ]
