# Generated by Django 4.2.16 on 2024-10-09 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('effbi_api', '0011_remove_tile_dashboard_id_alter_tile_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tile',
            name='organization',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='effbi_api.organization'),
        ),
    ]
