# Generated by Django 4.2.16 on 2024-10-09 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('effbi_api', '0012_tile_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tile',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tile',
            name='sql_query',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tile',
            name='tile_props',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
