# Generated by Django 4.2.16 on 2024-10-09 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('effbi_api', '0013_alter_tile_description_alter_tile_sql_query_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tile',
            name='component',
            field=models.CharField(default='', max_length=100),
        ),
    ]
