const testimonials = [
    {
      id: 1,
      // name: "Suzanna Sia",
      name: "Ava Chong",
      role: "Data Analyst at Google",
      image: "/assets/testimonials/profile-female.jpg",
      review: "“Thanks to this app, I can generate SQL queries and data visualization charts without any coding. It streamlined my process to obtain business insights.”",
      rating: 5,
    },
    {
      id: 2,
      // name: "Prof Soo Yuen Jien",
    name: "Shyamal Sankar",
      role: "Backend Developer at Autodesk, Final Year Project student specializing in NLP",
      image: "/assets/testimonials/male-4.jpg",
      review: "“I've seen a huge improvement in my workflow, allowing me to focus on generating insights without worrying about SQL syntax...”",
      rating: 5,
    },
    {
      id: 3,
      name: "Ritika Joshi",
      role: "Generative AI Software Developer at SAP",
      image: "/assets/testimonials/profile-female.jpg",
      review: "“Amazing, I can now manage database queries without writing a single line of code!”",
      rating: 5,
    },
    {
      id: 4,
      name: "Bryan Tan",
      role: "Data Analyst at Ampol",
      image: "/assets/testimonials/profile-male.jpg",
      review: "“It's amazing that this application is open-sourced. Eff BI helps me prepare my data analyses and generate SQL effectively.”",
      rating: 5,
    },
    {
      id: 5,
      name: "Ashley Wong",
      role: "Business Intelligence Analyst at Shopee",
      image: "/assets/testimonials/male-3.jpg",
      review: "“Eff BI will make my life so much easier, seamless generation of data visualizations! ”",
      rating: 5,
    },
    {
      id: 6,
      name: "Wang Ming Hao",
      role: "Software Engineer at Facebook",
      image: "/assets/testimonials/profile-male.jpg",
      review: "“Fantastic! This app provided the perfect guidance for generating complex SQL queries effortlessly.”",
      rating: 5,
    },
    {
      id: 7,
      name: "Isabelle",
      role: "Product Manager at Salesforce",
      image: "/assets/testimonials/profile-female.jpg",
      review: "“The interface is user-friendly and intuitive ... Eff BI really helped me visualize our business data effectively”",
      rating: 5,
    },
    {
      id: 8,
      name: "Chloe Wilson",
      role: "Data Visualization Specialist at Tableau",
      image: "/assets/testimonials/female-4.jpg",
      review: "“Eff BI has the tools needed to manage my data projects efficiently, especially for generating impactful visualizations!”",
      rating: 5,
    },
    {
      id: 9,
      name: "Grace Tang",
      role: "Data Engineer at LinkedIn",
      image: "/assets/testimonials/female-5.jpg",
      review: "“Highly effective features that have made my data visualization process so much easier and faster.”",
      rating: 5,
    },
  ];
  
  export default testimonials;  