const testimonials = [
    {
      id: 1,
      name: "Ava Johnson",
      role: "Data Analyst at Google",
      image: "/assets/testimonials/female-1.jpg",
      review: "“Thanks to this app, I can generate SQL queries and data visualization charts without any coding! It streamlined my reporting process.”",
      rating: 5,
    },
    {
      id: 2,
      name: "Chris Thompson",
      role: "Software Engineer at Facebook",
      image: "/assets/testimonials/male-1.jpg",
      review: "“The service is fantastic! This app provided the perfect guidance for generating complex SQL queries effortlessly.”",
      rating: 5,
    },
    {
      id: 3,
      name: "Sophia Lee",
      role: "Business Intelligence Analyst at Amazon",
      image: "/assets/testimonials/female-2.jpg",
      review: "“I love how easy it is to get started. This app made generating visualizations for my data so seamless!”",
      rating: 5,
    },
    {
      id: 4,
      name: "Ethan Clark",
      role: "Data Scientist at Microsoft",
      image: "/assets/testimonials/male-2.jpg",
      review: "“Great value for money! This app helped me prepare my data analyses and generate SQL effectively.”",
      rating: 5,
    },
    {
      id: 5,
      name: "Liam Harris",
      role: "Database Administrator at IBM",
      image: "/assets/testimonials/male-3.jpg",
      review: "“Absolutely brilliant service. I couldn't have managed my database queries better without writing a single line of code!”",
      rating: 5,
    },
    {
      id: 6,
      name: "Noah Robinson",
      role: "Technical Lead at Oracle",
      image: "/assets/testimonials/male-4.jpg",
      review: "“I've seen a huge improvement in my workflow, allowing me to focus on generating insights without worrying about SQL syntax!”",
      rating: 5,
    },
    {
      id: 7,
      name: "Isabelle Martinez",
      role: "Product Manager at Salesforce",
      image: "/assets/testimonials/female-3.jpg",
      review: "“The interface is user-friendly and intuitive. It really helped me visualize our business data effectively!”",
      rating: 5,
    },
    {
      id: 8,
      name: "Chloe Wilson",
      role: "Data Visualization Specialist at Tableau",
      image: "/assets/testimonials/female-4.jpg",
      review: "“It has everything I need to manage my data projects efficiently, especially for generating impactful visualizations!”",
      rating: 5,
    },
    {
      id: 9,
      name: "Grace Taylor",
      role: "Data Engineer at LinkedIn",
      image: "/assets/testimonials/female-5.jpg",
      review: "“Highly effective tools that have made my data visualization process so much easier and faster!”",
      rating: 5,
    },
  ];
  
  export default testimonials;  